### ISSUE TITLE
Checkbox field always required, even if not set as required (2.2)

### ISSUE THREAD

**Issue by distantnative** [getkirby/panel#635]

**Comment by bastianallgeier** [comment]
I think I already fixed this.

**Comment by distantnative** [comment]
It's still present when I tested #578 - in structure fields and outside:

```
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
    size:  large
  test:
    label: Notwendig?
    type: checkbox
  comments:
    label: Struktur
    type: structure
    fields:
      approved:
        label: Approved?
        type: checkbox
      name:
        label: Name
        type: text
``

**Comment by bastianallgeier** [comment]
damn :(

**Comment by distantnative** [comment]
Looking at #578 – I think `value()` being inconsistent could cause the issue.

**Comment by bastianallgeier** [comment]
can't check it out right now.

**Comment by distantnative** [comment]
I think it's caused by using `v::accepted` which only allows for positive bool "representations" (true, 1, "1", "true" etc.). But with the checkbox field we'd also need the negative ones.
