### ISSUE TITLE
Image field bug

### ISSUE THREAD

**Issue by jenstornell** [getkirby/panel#846]
I think I found a bug with the new image field.

![image](https://cloud.githubusercontent.com/assets/927011/15006852/3a689dd8-11d4-11e6-8ff0-f21dbde6109b.png)

As we can see the url is missing a slash.

>GET http://localhost/ekobyn-pattern.com/thumbsktiviteter/ice-skating-705183_1920-75x75.jpg 404 (Not Found)

**Comment by bastianallgeier** [comment]
I merged a PR from Lukas yesterday which might already fix that. Could you try to fetch the latest version from github and see if it works?

**Comment by jenstornell** [comment]
I downloaded nightly by the url in https://twitter.com/getkirby/status/549584880708096000 but the problem remains.

**Comment by bastianallgeier** [comment]
that's still the old version. you need to fetch it from github.
 
 
On Wed, May 4, 2016, at 09:01 AM, Jens Törnell wrote:
> I downloaded nightly by the url in
> https://twitter.com/getkirby/status/549584880708096000 but the problem
> remains.
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/getkirby/panel/issues/846#issuecomment-216761580

**Comment by jenstornell** [comment]
That link you posted goes to this page. I tested the development branch with the same issue.

**Comment by bastianallgeier** [comment]
I used my email client to reply to the message. Somehow that broken link sneaked in there. 

Did you already check out the latest develop branch of the core? 

Sorry for being so annoying with this stuff, but it's really hard to find the bug at the moment.

**Comment by jenstornell** [comment]
Now I tried it with the core as well and it's working! I was only downloading the development branch of the panel before.

Sorry for taking up your time!

**Comment by bastianallgeier** [comment]
Phew, I'm really really happy to hear that :) I was already about to go nuts. Thanks for your help!!
